name: Publish to pub.dev

on:
  push:
    tags:
      - 'core-v[0-9]+.[0-9]+.[0-9]+*'
      - 'cache-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for OIDC authentication
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Publish mineral
        if: startsWith(github.ref, 'refs/tags/core-v')
        run: dart pub publish --force
        working-directory: packages/core
      - name: Publish mineral_cache
        if: startsWith(github.ref, 'refs/tags/cache-v')
        run: dart pub publish --force
        working-directory: packages/cache
